from dpp.core.exception.aborted_exception import AbortedException